name: wow

on:
  workflow_dispatch:
  schedule:
    - cron: '00 09 * * *'

jobs:
  build:
    uses: Vladinator/wow-dbc-archive/.github/workflows/template.yml@main
    with:
      NAME: wow
      PRODUCT: wow
    runs-on: ubuntu-latest
