name: wow_classic

on:
  workflow_dispatch:
  schedule:
    - cron: '00 09 * * *'

jobs:
  build:
    uses: Vladinator/wow-dbc-archive/.github/workflows/template.yml@main
    inputs:
      NAME: wow_classic
      PRODUCT: wow_classic
