name: wow_classic

on:
  workflow_dispatch:
  schedule:
    - cron: '00 09 * * *'

env:
  NAME: wow_classic
  PRODUCT: wow_classic

jobs:
  build:
    uses: Vladinator/wow-dbc-archive/.github/workflows/template.yaml@main
    with:
      NAME: ${{ env.NAME }}
      PRODUCT: ${{ env.PRODUCT }}
    runs-on: ubuntu-latest
