name: wow_classic_ptr

on:
  workflow_dispatch:
  schedule:
    - cron: '00 01-23/08 * * *'

jobs:
  build:
    uses: ./.github/workflows/template.yml
    with:
      NAME: wow_classic_ptr
      PRODUCT: wow_classic_ptr
