name: wow_classic_era

on:
  workflow_dispatch:
  schedule:
    - cron: '00 09 * * *'

jobs:
  build:
    uses: Vladinator/wow-dbc-archive/.github/workflows/template.yml@main
    with:
      NAME: wow_classic_era
      PRODUCT: wow_classic_era
    runs-on: ubuntu-latest
