name: wow_classic_era

on:
  workflow_dispatch:
  schedule:
    - cron: '00 09 * * *'

jobs:
  build:
    uses: ./.github/workflows/template.yml
    with:
      NAME: wow_classic_era
      PRODUCT: wow_classic_era
